name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Deploy to Azure VM using SCP
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.AZURE_HOST }}
        username: ${{ secrets.AZURE_USERNAME }}
        key: ${{ secrets.AZURE_SSH_KEY }}
        passphrase: ${{ secrets.AZURE_SSH_KEY_PASSPHRASE }}
        source: "./*"
        target: "/tmp"

    - name: Run remote commands to update Nginx
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.AZURE_HOST }}
        username: ${{ secrets.AZURE_USERNAME }}
        key: ${{ secrets.AZURE_SSH_KEY }}
        passphrase: ${{ secrets.AZURE_SSH_KEY_PASSPHRASE }}
        script: |
          sudo cp -r /tmp/* /var/www/html/
          sudo systemctl restart nginx
